apiVersion: v1
kind: Secret
metadata:
  name: todolist-secret
  namespace: todolist-grupo-02
type: Opaque

stringData:
  SESSION_KEY: "Agora-Vai-2026"
  ADMIN_USER: "admin"
  ADMIN_PASSWORD: "123@Mudar"
  CLEANUP_TOKEN: "cleanup-token-2026"